[package]
name = "nrf5x"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
kernel = { path = "../../kernel" }

[features]
default = []

nrf51 = []
nrf52 = []
