[package]
name = "tm4c129x"
version = "0.1.0"
authors = ["Alexander Müllner <es16m017@technikum-wien.at>"]

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
kernel = { path = "../../kernel" }