[package]
name = "nrf51dk"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"

[profile.dev]
panic = "abort"
lto = false
opt-level = "z"
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
debug = true

[dependencies]
cortexm0 = { path = "../../../arch/cortex-m0" }
capsules = { path = "../../../capsules" }
kernel = { path = "../../../kernel" }
nrf51 = { path = "../../../chips/nrf51" }
nrf5x = { path = "../../../chips/nrf5x" }
